name: TreasureChest
main: awzaw\treasurechest\Main
version: 1.2.1-1.alpha8
author: Awzaw
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8]
load: POSTWORLD
commands:
 tchest:
  permission: tchest
  description: Add a new treasure chest
  usage: /tchest
permissions:
   tchest:
    default: op