name: TreasureChest
main: awzaw\treasurechest\Main
version: 1.2
author: Awzaw
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
load: POSTWORLD
commands:
 tchest:
  permission: tchest
  description: Add a new treasure chest
  usage: /tchest
permissions:
   tchest:
    default: op